<?php 
    $baseurl = $block->getBaseUrl();
?>
<div id="popup-modal">
    <form action = "<?php echo $baseurl."hpopup/index/popup"; ?>" method = "post" autocomplete="off">
        <fieldset>
            <legend>Personal Details</legend>    
            <p>
                <label>First name: <input name="firstName" required/></label>
            </p>
            <p>
                <label>Last name: <input name="lastName" required/></label>
            </p>
            <p>
            
            <label for="gender">Gender :</label>
            <select name="gender" id="gender">
                <option value="male">Male</option>
                <option value="female">Female</option>
                <option value="other">Other</option>
            </select>
            </p>
            <p>
                <label>Email:<input type="email" name="email" required/></label>
            </p>
            <p>
                <button type="submit" name="submit">Submit</button>
            </p>
        </fieldset>
    </form>
</div>
